name: 'brasil_dbt'
version: '1.0.0'
profile: 'brasil_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# ─── SEEDS ───────────────────────────────────────────────────────────────────
# ⭐ PAS de +schema = dbt utilise directement le dataset du profiles.yml
seeds:
  brasil_dbt:
    # Rien ici, ou juste des configs de colonnes si besoin

# ─── MODÈLES ─────────────────────────────────────────────────────────────────
# ⭐ PAS de +schema = dbt utilise directement le dataset du profiles.yml
models:
  brasil_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table