# dbt_project.yml

name: 'brasil_dbt'
version: '1.0.0'
profile: 'brasil_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des seeds pour qu'ils soient chargés dans le bon dataset
seeds:
  brasil_dbt:
    +schema: "{{ 'e_com_prod' if target.name == 'prod' else 'e_com_dev' }}"

# Configuration des modèles
models:
  brasil_dbt:
    staging:
      +materialized: view
      +schema: "{{ 'e_com_prod' if target.name == 'prod' else 'e_com_dev' }}"
    intermediate:
      +materialized: view
      +schema: "{{ 'e_com_prod' if target.name == 'prod' else 'e_com_dev' }}"
    mart:
      +materialized: table
      +schema: "{{ 'e_com_prod' if target.name == 'prod' else 'e_com_dev' }}"